### ISSUE TITLE
Change on the website/API means neither functions work anymore

### ISSUE THREAD

**Issue by salix-d** [biocodellc/rppo#10]
Hi,

I spent most of yesterday rewritting the `ppo_data` function to make it work with the new website.
I also notice it gets you the source but not the traits, so I added a function to retrieve them.

I'll fork and make a branch for it. Was just wondering if it's still maintained? 
From previous issues, it seems like you manage the API as well?
Is there documentation for it?
I went with what I found in the source JS code of the webpage as I couldn't find it.
Also, might I suggest grouping the traits data in the JSON? (like all pheno/taxonomic/intensity/temp/etc. realated data together)

**Comment by salix-d** [comment]
I made a pull request for the fixes and more #11

**Comment by jdeck88** [comment]
I merged the PR... thanks.  A couple of questions:
1) the CRAN build is old and we will need to resubmit... let me know if you want to see it on CRAN spedifically. otherwise, i removed the CRAN reference from the README and just providing the github installation method as it has been removed from CRAN.
2) you've done alot of work on this, do you want to be added to the AUTHOR list?
There are more issues with the code that needs to be fixed... its been a few years since i've touched it.  However, i think that we will be working on this codebase some more in the coming few years since we just received word of a funded NSF grant proposal for working on this some more... send me email if you are interested in working on this further, i believe that we could compensate you for some of your time if you are interested (but won't get started until October, i think)
